[tool.ruff]
target-version = "py311"
line-length = 100
exclude = ["venv", ".venv", ".ci-venv", ".ci-venv2"]

[tool.ruff.lint]
ignore = ["E402"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["F401", "F841"]
